#spring:
#  security:
#    user:
#      name: test
#      password: 1111

logging:
  level:
    root: info
    com.webAdmin: debug
    org:
       apache:
         ibatis: debug
    bootAdmin: debug
    org.springframework.jdbc.core.JdbcTemplate: debug

mybatis:
  type-aliases-package: com.webAdmin.dao
#  config-location: classpasth:config/mybatis-config.xml

server:
  port: 8000
  servlet:
    session:
      timeout: 600m


spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
      url: jdbc:oracle:thin:@upcns.iptime.org:21521:orcl
      driver-class-name: oracle.jdbc.OracleDriver
      username: DEMOADMIN
      password: DEMOADMIN
  thymeleaf:
    prefix: classpath:/public/thymeleaf/
